config/routes.rb
Rails.application.routes.draw do
  resources :accounts

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @account = Account.new
  end

  def index
    @accounts = Account.all
  end

  def create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/accounts/create.html.erb</p>

app/views/accounts/index.html.erb
<h1>Accounts</h1>
  <table class="hoverable">
    <thead>
      <tr>
        <th data-field="Name">Name</th>
        <th data-field="Zipcode">Zipcode</th>
        <th data-field="City">City</th>
        <th data-field="State">State</th>
        <th data-field="Longitude">Longitude</th>
        <th data-field="Latitude">Latitude</th>
        <th data-field="Pro">Pro</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><h5>  <%= account.name %></h5></td>
        <td>  <%= account.zipcode %></td>
        <% if account.city %>
          <td>  <%= account.city %>,</td>
          <td>  <%= account.state %></td>
          <td>  <%= account.latitude %></td>
          <td>  <%= account.longitude %></td>
          <td>  <%= account.pro %></td>
        <% else %>
          <td col-span="4"class="green-text">Loading Data</td>
        <% end %>
      </tr>
    <% end %>
  </table>

app/views/accounts/new.html.erb
<h1>Add a new Account</h1>
<div class="row">

</div>
<%= form_for @account, class: "col s12" do |f| %>
  <div class="row">
    <div class="input-field col s6">
    <%= f.label :name%><%=f.text_field :name %>
    </div>
    <div class="input-field col s6">
      <%= f.label :zipcode %><%= f.text_field :zipcode %>
    </div>
  </div>
  <%= f.button "Submit", class: "btn orange waves-effect waves-light"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geolocator</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body >
    <nav class="light-blue lighten-1" role="navigation">
      <div class="nav-wrapper container">
        <ul class="hide-on-med-and-down">
          <li><%= link_to "Accounts",accounts_path, class: "brand-logo" %></li>
        </ul>
        <ul class="right">
          <li><%= link_to "new Account", new_account_path, class: "right" %></li>
        </ul>
      </div>
    </nav>
    <div class="container">
    
    <%= yield %>
    
    </div>


  </body>
</html>